---
name: "Polyglot"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "0.8.12.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "Maronato"
overview: "Multi-language metadata support through library mirroring with hardlinks."
description: |
  Serve your Jellyfin library in multiple languages without duplicating files.
  Creates language-specific mirror libraries using hardlinks, allowing different
  users to see different metadata languages. Supports LDAP integration for
  automatic language assignment based on group membership.
category: "General"
artifacts:
  - "Jellyfin.Plugin.Polyglot.dll"
changelog: "See GitHub releases for full changelog."
repositoryUrl: "https://github.com/Maronato/jellyfin-plugin-polyglot"
